### ISSUE TITLE
Load test data

### ISSUE THREAD

**Issue by Magegee37** [rafael-weilharter/ATLAS-MVSNet#4]
When I use the DTU dataset for testing, it cannot be used. I tried to write a piece of code myself, but failed. How can I solve this problem? Looking forward to your reply, thank you.

**Comment by rafael-weilharter** [comment]
Did you download the original dataset?
Rectified images and depth maps should be at a resolution of 1600x1200. With this data, the provided Dataloader should be able to handle the rest. There are some resources for the DTU dataset out there that use down-scaled images and/or depth maps.

**Comment by Magegee37** [comment]
Thank you for your response. I found this problem in my paper. Previously, I used a tailored dataset, not the original 1200 × 1600 resolution. Also, in Blended MVS datasets, do you need to use high-resolution ones? However, I am testing the TNT dataset using the trained file you provided and find that the effect is not good.

**Comment by rafael-weilharter** [comment]
Yes, also on Blended MVS we trained with the high-resolution images.
For T&T it is important to set the `--interval_scale` flag to the correct values. Scenes that focus on an object that is close wrt the background should have this value set between 0.1 and 0.3 (e.g. Family, Francis, Horse). Other scenes are in the range of 0.5 - 1.0.
Furthermore, it can help to set the flags `--input_scale=2` and `--output_scale=4`, because the network is aimed at much higher resolutions than provided by the dataset. This will just upscale the input images by a factor of 2 and output a depth map that is half the size of the original images (otherwise there might be too many points in the pointcloud).
HTH

**Comment by Magegee37** [comment]
Thank you very much for your excellent work.
